### ISSUE TITLE
Is the cars dataset still available?

### ISSUE THREAD

**Issue by HydrogenSulfate** [edoRemelli/MeshSDF#11]
I see the google drive dataset is outdated and not available, is there any other valid download url?

**Comment by hanyangyu1021** [comment]
Hi, have you got the dataset?

**Comment by HydrogenSulfate** [comment]
> Hi, have you got the dataset?

No, it seems that this repo is no longer maintained, so the ShapeNetV1 dataset cannot be directly downloaded. However, I found [instructions](https://blog.csdn.net/qq_38677322/article/details/110957634) on how to create the dataset on other websites. You can still use the dataset generation scripts provided in the repo to generate interior and exterior points along with their SDF based on your own mesh geometry, which can serve as training data. Most of the sdf data of ShapeNetV1 can be generated except for certain shapes which meets errors.
