### ISSUE TITLE
Code for single-view reconstruction

### ISSUE THREAD

**Issue by hakanyi** [edoRemelli/MeshSDF#3]
Thanks for this work, I really enjoyed reading your paper! 

I'm excited to use parts of it, especially the single-view reconstruction part, in a project of mine. Are you guys planning on releasing the code anytime soon? Thanks again!

**Comment by jianglongye** [comment]
Hope to use SVR code sooner. Thanks!

**Comment by b7leung** [comment]
Thanks for the great work! I found it really interesting. Is there any updates or approximate date for releasing the code for single-view reconstruction?

**Comment by edoRemelli** [comment]
sorry all for the wait, we have finally released code for SVR!
