### ISSUE TITLE
Complete Data

### ISSUE THREAD

**Issue by ChengChen2020** [edoRemelli/MeshSDF#9]
Hi,

Could you please provide pre-processed ShapeNet data that contains all categories? Thanks.

**Comment by bguillard** [comment]
Hello! You can find them [here](https://github.com/Xharlie/DISN#prepare-the-sdf-ground-truth-and-the-marching-cube-reconstructed-ground-truth-models), provided by the authors of [DISN](https://arxiv.org/abs/1905.10711).
